package ua.edboservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2016-03-07T15:21:33.582+02:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://edboservice.ua/", name = "EDBOPersonSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EDBOPersonSoap {

    @WebMethod(operationName = "PersonRequestBenefitsGet", action = "http://edboservice.ua/PersonRequestBenefitsGet")
    @RequestWrapper(localName = "PersonRequestBenefitsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestBenefitsGet")
    @ResponseWrapper(localName = "PersonRequestBenefitsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestBenefitsGetResponse")
    @WebResult(name = "PersonRequestBenefitsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonRequestBenefits personRequestBenefitsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_PersonRequest", targetNamespace = "http://edboservice.ua/")
        int idPersonRequest
    );

    @WebMethod(operationName = "PersonsFind", action = "http://edboservice.ua/PersonsFind")
    @RequestWrapper(localName = "PersonsFind", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonsFind")
    @ResponseWrapper(localName = "PersonsFindResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonsFindResponse")
    @WebResult(name = "PersonsFindResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonsFind personsFind(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "FIOMask", targetNamespace = "http://edboservice.ua/")
        java.lang.String fioMask,
        @WebParam(name = "DocumentSeries", targetNamespace = "http://edboservice.ua/")
        java.lang.String documentSeries,
        @WebParam(name = "DocumentNumber", targetNamespace = "http://edboservice.ua/")
        java.lang.String documentNumber,
        @WebParam(name = "Ids_DocumentTypes", targetNamespace = "http://edboservice.ua/")
        java.lang.String idsDocumentTypes,
        @WebParam(name = "Hundred", targetNamespace = "http://edboservice.ua/")
        int hundred,
        @WebParam(name = "PersonCodeU", targetNamespace = "http://edboservice.ua/")
        java.lang.String personCodeU,
        @WebParam(name = "Filters", targetNamespace = "http://edboservice.ua/")
        java.lang.String filters
    );

    @WebMethod(operationName = "PersonDocumentTypesGet", action = "http://edboservice.ua/PersonDocumentTypesGet")
    @RequestWrapper(localName = "PersonDocumentTypesGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonDocumentTypesGet")
    @ResponseWrapper(localName = "PersonDocumentTypesGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonDocumentTypesGetResponse")
    @WebResult(name = "PersonDocumentTypesGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonDocumentTypes personDocumentTypesGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage
    );

    @WebMethod(operationName = "PersonRequestDocumentSubjectsGet", action = "http://edboservice.ua/PersonRequestDocumentSubjectsGet")
    @RequestWrapper(localName = "PersonRequestDocumentSubjectsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestDocumentSubjectsGet")
    @ResponseWrapper(localName = "PersonRequestDocumentSubjectsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestDocumentSubjectsGetResponse")
    @WebResult(name = "PersonRequestDocumentSubjectsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonRequestDocumentSubjects personRequestDocumentSubjectsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_PersonRequest", targetNamespace = "http://edboservice.ua/")
        int idPersonRequest
    );

    @WebMethod(operationName = "PersonRequestOlympiadsAwardsGet", action = "http://edboservice.ua/PersonRequestOlympiadsAwardsGet")
    @RequestWrapper(localName = "PersonRequestOlympiadsAwardsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestOlympiadsAwardsGet")
    @ResponseWrapper(localName = "PersonRequestOlympiadsAwardsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestOlympiadsAwardsGetResponse")
    @WebResult(name = "PersonRequestOlympiadsAwardsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonRequestOlympiadsAwards personRequestOlympiadsAwardsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_PersonRequest", targetNamespace = "http://edboservice.ua/")
        int idPersonRequest
    );

    @WebMethod(operationName = "PersonBenefitsGet", action = "http://edboservice.ua/PersonBenefitsGet")
    @RequestWrapper(localName = "PersonBenefitsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonBenefitsGet")
    @ResponseWrapper(localName = "PersonBenefitsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonBenefitsGetResponse")
    @WebResult(name = "PersonBenefitsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonBenefits personBenefitsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_Person", targetNamespace = "http://edboservice.ua/")
        int idPerson
    );

    @WebMethod(operationName = "PersonRequestQuotasGet", action = "http://edboservice.ua/PersonRequestQuotasGet")
    @RequestWrapper(localName = "PersonRequestQuotasGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestQuotasGet")
    @ResponseWrapper(localName = "PersonRequestQuotasGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestQuotasGetResponse")
    @WebResult(name = "PersonRequestQuotasGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonRequestQuotas personRequestQuotasGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_PersonRequest", targetNamespace = "http://edboservice.ua/")
        int idPersonRequest
    );

    @WebMethod(operationName = "PersonDocumentsSubjectsGet", action = "http://edboservice.ua/PersonDocumentsSubjectsGet")
    @RequestWrapper(localName = "PersonDocumentsSubjectsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonDocumentsSubjectsGet")
    @ResponseWrapper(localName = "PersonDocumentsSubjectsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonDocumentsSubjectsGetResponse")
    @WebResult(name = "PersonDocumentsSubjectsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonDocumentsSubjects personDocumentsSubjectsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_PersonDocument", targetNamespace = "http://edboservice.ua/")
        int idPersonDocument,
        @WebParam(name = "Id_Person", targetNamespace = "http://edboservice.ua/")
        int idPerson,
        @WebParam(name = "Id_PersonDocumentType", targetNamespace = "http://edboservice.ua/")
        int idPersonDocumentType
    );

    @WebMethod(operationName = "GetLastError", action = "http://edboservice.ua/GetLastError")
    @RequestWrapper(localName = "GetLastError", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.GetLastError")
    @ResponseWrapper(localName = "GetLastErrorResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.GetLastErrorResponse")
    @WebResult(name = "GetLastErrorResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDLastError getLastError(
        @WebParam(name = "GUIDSession", targetNamespace = "http://edboservice.ua/")
        java.lang.String guidSession
    );

    @WebMethod(operationName = "PersonAddressesGet2", action = "http://edboservice.ua/PersonAddressesGet2")
    @RequestWrapper(localName = "PersonAddressesGet2", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonAddressesGet2")
    @ResponseWrapper(localName = "PersonAddressesGet2Response", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonAddressesGet2Response")
    @WebResult(name = "PersonAddressesGet2Result", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonAddresses2 personAddressesGet2(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "PersonCodeU", targetNamespace = "http://edboservice.ua/")
        java.lang.String personCodeU,
        @WebParam(name = "Id_PersonAddress", targetNamespace = "http://edboservice.ua/")
        int idPersonAddress
    );

    @WebMethod(operationName = "PersonDocumentsGet", action = "http://edboservice.ua/PersonDocumentsGet")
    @RequestWrapper(localName = "PersonDocumentsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonDocumentsGet")
    @ResponseWrapper(localName = "PersonDocumentsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonDocumentsGetResponse")
    @WebResult(name = "PersonDocumentsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonDocuments personDocumentsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "PersonCodeU", targetNamespace = "http://edboservice.ua/")
        java.lang.String personCodeU,
        @WebParam(name = "Id_PersonDocumentType", targetNamespace = "http://edboservice.ua/")
        int idPersonDocumentType,
        @WebParam(name = "Id_PersonDocument", targetNamespace = "http://edboservice.ua/")
        int idPersonDocument,
        @WebParam(name = "UniversityKode", targetNamespace = "http://edboservice.ua/")
        java.lang.String universityKode,
        @WebParam(name = "IsEntrantDocument", targetNamespace = "http://edboservice.ua/")
        int isEntrantDocument
    );

    @WebMethod(operationName = "PersonRequestExaminationsGet", action = "http://edboservice.ua/PersonRequestExaminationsGet")
    @RequestWrapper(localName = "PersonRequestExaminationsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestExaminationsGet")
    @ResponseWrapper(localName = "PersonRequestExaminationsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonRequestExaminationsGetResponse")
    @WebResult(name = "PersonRequestExaminationsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonRequestExaminations personRequestExaminationsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "Id_PersonRequest", targetNamespace = "http://edboservice.ua/")
        int idPersonRequest
    );

    @WebMethod(operationName = "PersonOlympiadsAwardsGet", action = "http://edboservice.ua/PersonOlympiadsAwardsGet")
    @RequestWrapper(localName = "PersonOlympiadsAwardsGet", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonOlympiadsAwardsGet")
    @ResponseWrapper(localName = "PersonOlympiadsAwardsGetResponse", targetNamespace = "http://edboservice.ua/", className = "ua.edboservice.PersonOlympiadsAwardsGetResponse")
    @WebResult(name = "PersonOlympiadsAwardsGetResult", targetNamespace = "http://edboservice.ua/")
    public ua.edboservice.ArrayOfDPersonOlympiadsAwards personOlympiadsAwardsGet(
        @WebParam(name = "SessionGUID", targetNamespace = "http://edboservice.ua/")
        java.lang.String sessionGUID,
        @WebParam(name = "ActualDate", targetNamespace = "http://edboservice.ua/")
        java.lang.String actualDate,
        @WebParam(name = "Id_Language", targetNamespace = "http://edboservice.ua/")
        int idLanguage,
        @WebParam(name = "PersonCodeU", targetNamespace = "http://edboservice.ua/")
        java.lang.String personCodeU,
        @WebParam(name = "Id_PersonRequestSeasons", targetNamespace = "http://edboservice.ua/")
        int idPersonRequestSeasons
    );
}
