package org.lnu.is.integration.cases.config

import org.lnu.is.integration.cases.BaseIntegrationTest
import org.lnu.is.integration.config.OrderByType
import org.lnu.is.integration.config.OrderBy
object Configuration extends BaseIntegrationTest {
/*
 assets/1/address
 * */
  
/**
 * format:
	Map(
	   "name" -> "",
	   "url" -> "",
	   "title" -> " Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
		"chackWithOutParemetrs" -> false
     )
 */
  /**
   *щоб вимкнути тести певної групи траба відповідно у globalCongiguration відповідне значення поставити false
   */
val data =List(
	Map(
	   "name" -> "adresstype",
	   "url" -> "/addresstypes",
	   "title" -> "Address Type Integration Test",
	   "filds" -> List[String]("id", "name", "abbrName","uri"),
	   "filter" -> Map[String,Any]("id" -> 1, "name" -> "as", "abbrName" -> "asd"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("abbrName", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   //TODO:Add CRUD opertions test
	Map(
	   "name" -> "adminunit",
	   "url" -> "/adminunits",
	   "title" -> "Admin Unit Integration Test",
	   "filter" -> Map[String,Any]("adminUnitTypeId"->1, "parentId" -> 1, "identifier"->"001", "identifier1" -> "010" , "identifier2" -> "010", "identifier3" ->"00051" , "name" -> "Cd", "begDate"-> "2015-02-07", "endDate" -> "2015-03-01" ),
	   "order" -> List[OrderBy](new OrderBy("adminUnitTypeId", OrderByType.ASC), new OrderBy("parentId", OrderByType.ASC), new OrderBy("identifier", OrderByType.DESC) , new OrderBy("identifier1", OrderByType.DESC)  , new OrderBy("identifier2", OrderByType.ASC), new OrderBy("identifier3", OrderByType.ASC) , new OrderBy("name", OrderByType.DESC) , new OrderBy("begDate", OrderByType.ASC), new OrderBy("endDate", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "adminunittype",
	   "url" -> "/adminunits/types",
	   "title" -> "Admin Unit Type Integration Test",
	   "filds" -> List[String]("id", "name", "abbrName", "uri"),
	   "filter" -> Map[String,Any]("id" -> 1, "name" -> "as", "abbrName" -> "asd"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("abbrName", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "asset", 
	   "url" -> "/assets",
	   "title" -> "Asset Integration Test",
	   "filter" -> Map[String,Any]("id" -> 1, "invNum" -> "as", "prodDate" -> "2015-02-07",  "endDate"-> "2015-02-07",  "serialNum"-> "serl",  "begDate"-> "2015-02-07", "amount"-> 3,  "price"-> 100,  "suma"-> 300,  "assetTypeId"-> 1,  "assetStatusId"-> 1,  "assetStateId"-> 1,  "description"-> "description",  "name"-> "name"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("invNum", OrderByType.DESC),  new OrderBy("prodDate", OrderByType.DESC),  new OrderBy("endDate", OrderByType.ASC) ,  new OrderBy("serialNum", OrderByType.DESC),  new OrderBy("begDate", OrderByType.ASC), new OrderBy("amount", OrderByType.DESC),  new OrderBy("price", OrderByType.DESC),  new OrderBy("suma", OrderByType.ASC),  new OrderBy("assetTypeId", OrderByType.DESC),  new OrderBy("assetStatusId", OrderByType.DESC),  new OrderBy("assetStateId", OrderByType.ASC),  new OrderBy("description", OrderByType.DESC),  new OrderBy("name", OrderByType.DESC)),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "assetaddress",
	   "url" -> "/assets/${assetId}/addresses",
	   "title" -> "Asset Address Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),
	   
	Map(
	   "name" -> "assetstate",
	   "url" -> "/assets/states",
	   "title" -> "Asset State Integration Test",
	   "filds" -> List[String]("id", "name", "uri"),
	   "filter" -> Map[String, Any]("id" -> 1, "name" -> "as"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "assetstatus",
	   "url" -> "/assets/statuses",
	   "title" -> "Asset Status Integration Test",
	   "filds" -> List[String]("id", "name", "uri"),
	   "filter" -> Map[String, Any]("id" -> 1, "name" -> "as"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "assettype",
	   "url" -> "/assets/types",
	   "title" -> "Asset Type Integration Test",
	   "filds" -> List[String]("id", "name", "abbrName", "uri"),
	   "filter" -> Map[String,Any]("id" -> 1, "name" -> "as", "abbrName" -> "asd"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("abbrName", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	  
	Map(
	   "name" -> "benefit",
	   "url" -> "/benefits",
	   "title" -> "Benefit Integration Test",
	   "filter" -> Map[String,Any]("abbrName" -> 1, "name" -> "as", "endDate"-> "2012-01-01", "begDate"-> "2012-02-02",  "benefitTypeId"-> 1,  "description"-> "DEscription"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("endDate", OrderByType.ASC) , new OrderBy("begDate", OrderByType.ASC)  ,  new OrderBy("benefitTypeId", OrderByType.ASC),  new OrderBy("description", OrderByType.DESC)),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	  
	Map(
	   "name" -> "benefittype",
	   "url" -> "/benefits/types",
	   "title" -> "Benefit Type Integration Test",
	   "filds" -> List[String]("id", "name", "priority", "uri"),
	   "filter" -> Map[String,Any]("id" -> 1, "name" -> "as", "priority" -> 1),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("priority", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "contattype",
	   "url" -> "/contacts/types",
	   "title" -> "Contact Type Integration Test",
	   "filds" -> List[String]("id", "name", "abbrName", "uri"),
	   "filter" -> Map[String,Any]("id" -> 1, "name" -> "as", "abbrName" -> "asd"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("abbrName", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "coursetype",
	   "url" -> "/courses/types",
	   "title" -> "Course Type Integration Test",
	   "filds" -> List[String]("id", "name", "abbrName", "uri"),
	   "filter" -> Map[String,Any]("id" -> 1, "name" -> "as", "abbrName" -> "asd"),
	   "order" -> List[OrderBy](new OrderBy("id", OrderByType.ASC), new OrderBy("name", OrderByType.DESC), new OrderBy("abbrName", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),

	   // TODO: Add releation
	Map(
	   "name" -> "degree",
	   "url" -> "/degrees",
	   "title" -> "Degree Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("personId" -> 1, "degreeTypeId" -> 1),
	   "order" -> List[OrderBy](new OrderBy("personId", OrderByType.ASC), new OrderBy("degreeTypeId", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),
	
	Map(
	   "name" -> "degretype",
	   "url" -> "/degrees/types",
	   "title" -> "Degree Types Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "test", "name" -> "sdf"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "department",
	   "url" -> "/departments",
	   "title" -> "Department Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("parentId" -> 1, "departmentTypeId" -> 1, "abbrName" -> "an", "name" -> "n", "manager" -> "men", "identifir" -> "10.01.01", "begDate" -> "2015-02-02", "endDate" -> "2015-02-02"),//TODO: Add "oder"->1
	   "order" -> List[OrderBy](new OrderBy("parentId", OrderByType.ASC) , new OrderBy("orderId", OrderByType.DESC) , new OrderBy("departmentTypeId", OrderByType.ASC) , new OrderBy("abbrName", OrderByType.ASC) , new OrderBy("name", OrderByType.ASC) , new OrderBy("manager", OrderByType.DESC) , new OrderBy("identifir", OrderByType.DESC) , new OrderBy("begDate", OrderByType.DESC) , new OrderBy("endDate", OrderByType.DESC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "departmentaddress",
	   "url" -> "/departments/${departmentId}/addresses",
	   "title" -> "Department Address Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "departmentcontact",
	   "url" -> "/departments/${departmentId}/contacts",
	   "title" -> "Department Contact Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "departmentname",
	   "url" -> "/departments/${departmentId}/names",
	   "title" -> "Department Name Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "departmentspecialty",
	   "url" -> "/departments/${departmentId}/specialties",
	   "title" -> "Department Specialty Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),
	 
	Map(
	   "name" -> "departmenttype",
	   "url" -> "/departments/types",
	   "title" -> "Department Type Integration Test",
	   "filds" -> List[String]("id",  "name", "uri"), // TODO: add "abbrName"
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "dutytepe",
	   "url" -> "/duties/types",
	   "title" -> "Duty Status Integration Test",
	   "filds" -> List[String]("id", "name", "uri"),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   ),
	
	Map(
	   "name" -> "educationtype",
	   "url" -> "/educations/types",
	   "title" -> "Education Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC) ),
	   "pathData" -> "data/education/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),
   	
	Map(
	   "name" -> "educationformtype",
	   "url" -> "/educations/forms/types",
	   "title" -> "Educations Form Types Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("name" -> "new"),
	   "order" -> List[OrderBy](new OrderBy("name", OrderByType.ASC) ),
	   "pathData" -> "data/education/form/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),
   	//TODO:Is not test
   	Map(
	   "name" -> "employee",
	   "url" -> "/employees",
	   "title" -> "Employee Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("name" -> "new"),
	   "order" -> List[OrderBy](new OrderBy("name", OrderByType.ASC) ),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),
   	   
	Map(
	   "name" -> "employeestatus",
	   "url" -> "/employees/statuses",
	   "title" -> "Employee Status Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.DESC) ),
	   "pathData" -> "data/employee/status/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "employeetype",
	   "url" -> "/employees/types",
	   "title" -> "Employee Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC)  ),
	   "pathData" -> "data/employee/types/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "enrolment",
	   "url" -> "/enrolments",
	   "title" -> "Enrolment Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "enrolmentbenefit",
	   "url" -> "/enrolments/${enrolmentId}/benefits",
	   "title" -> "Enrolment Benefit Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "enrolmentstatuse",
	   "url" -> "/enrolments/${enrolmentId}/statuses",
	   "title" -> "Enrolment Status Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "enrolmentstatustype",
	   "url" -> "/enrolments/statustypes",
	   "title" -> "Enrolment Status Types Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "qwe", "name" -> "nqm","description" -> "desc"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC), new OrderBy("description", OrderByType.ASC) ),
	   "pathData" -> "data/enrolment/statustype/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "enrolmentsubject",
	   "url" -> "/enrolments/subjects",
	   "title" -> "Enrolment Subject Types Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("parentId" -> 3, "abbrName" -> "укр", "name" ->"213","isTesting" -> 1),
	   "order" -> List[OrderBy](new OrderBy("parentId", OrderByType.ASC) , new OrderBy("abbrName", OrderByType.DESC) , new OrderBy("name", OrderByType.ASC) ,new OrderBy("isTesting", OrderByType.ASC) ),
	   "pathData" -> "data/enrolment/subject/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "enrolmenttype",
	   "url" -> "/enrolments/types",
	   "title" -> "Enrolment Types Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC)  ),
	   "pathData" -> "data/enrolment/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "familytype",
	   "url" -> "/families/types",
	   "title" -> "Family Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.ASC)),
	   "pathData" -> "data/family/types/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "gendertype",
	   "url" -> "/gendertypes",
	   "title" -> "Gender Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "123", "name" -> "neme"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.DESC) , new OrderBy("name", OrderByType.DESC) ),
	   "pathData" -> "data/gendertype/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "honortype",
	   "url" -> "/honors/types",
	   "title" -> "Honor Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any]("abbrName" -> "abr", "name" -> "df"),
	   "order" -> List[OrderBy](new OrderBy("abbrName", OrderByType.ASC), new OrderBy("name", OrderByType.DESC)),
	   "pathData" -> "data/honor/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> true,
	   "checkOrderOne" -> true,
	   "checkFilter" -> true,
	   "checkFilterOne"-> true,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "language",
	   "url" -> "/languages",
	   "title" -> "Language Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/language/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "marriedtype",
	   "url" -> "/marriedtypes",
	   "title" -> "Married Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/marriedtype/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "operationtype",
	   "url" -> "/operationtypes",
	   "title" -> "Operation Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/operation/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "order",
	   "url" -> "/orders",
	   "title" -> "Order Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "ordertype",
	   "url" -> "/orders/types",
	   "title" -> "Order Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/order/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "papertype",
	   "url" -> "/papers/types",
	   "title" -> "Paper Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/paper/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "paperusage",
	   "url" -> "/papers/usages",
	   "title" -> "Paper Usage Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/paper/usage/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "partner",
	   "url" -> "/partners",
	   "title" -> "Partner Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "person",
	   "url" -> "/persons",
	   "title" -> "Person Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "personaddress",
	   "url" -> "/persons/${personId}/addresses",
	   "title" -> "Person Address Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personaward",
	   "url" -> "/persons/${personId}/awards",
	   "title" -> "Person Award Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personcontact",
	   "url" -> "/persons/${personId}/contacts",
	   "title" -> "Person Contact Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personeducation",
	   "url" -> "/persons/${personId}/educations",
	   "title" -> "Person Education Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personenrolmentsubject",
	   "url" -> "/persons/${personId}/enrolmentsubjects",
	   "title" -> "Person Enrolment Subject Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personfamily",
	   "url" -> "/persons/${personId}/families",
	   "title" -> "Person Family Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personlanguage",
	   "url" -> "/persons/${personId}/languages",
	   "title" -> "Person Language Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personname",
	   "url" -> "/persons/${personId}/names",
	   "title" -> "Person Name Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "personpaper",
	   "url" -> "/persons/${personId}/papers",
	   "title" -> "Person Paper Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "persontype",
	   "url" -> "/persons/types",
	   "title" -> "Person Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/person/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "publicactivity",
	   "url" -> "/publicactivities",
	   "title" -> "Public Activity Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "publicactivityaward",
	   "url" -> "/publicactivities/{publicActivityId}/awards",
	   "title" -> "Public Activity Award Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "publicactivitytype",
	   "url" -> "/publicactivities/types",
	   "title" -> "Public Activity Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/publicactivity/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "reason",
	   "url" -> "/reasons",
	   "title" -> "Reason Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/reason/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "salarytype",
	   "url" -> "/sallaries/types",
	   "title" -> "Salary Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/salary/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "specialty",
	   "url" -> "/specialties",
	   "title" -> "Specialty Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "specialtytype",
	   "url" -> "/specialties/types",
	   "title" -> " Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/specialty/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "specoffer",
	   "url" -> "/specoffers",
	   "title" -> "Specoffer Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "specofferbenefit",
	   "url" -> "/specoffers/${specofferId}/benefits",
	   "title" -> "Specoffer Benefit Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "specoffersubject",
	   "url" -> "/specoffers/${specofferId}/subjects",
	   "title" -> "Specoffer Subject Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "specoffertype",
	   "url" -> "/specoffers/types",
	   "title" -> "Specoffer Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/specoffer/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	//TODO:Add begDate and End Date
	Map(
	   "name" -> "specofferwave",
	   "url" -> "/specoffers/${specofferId}/waves",
	   "title" -> "Specoffer Wave Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> false
	   ),

	Map(
	   "name" -> "streettype",
	   "url" -> "/streets/types",
	   "title" -> "Street Types Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/street/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "studyplancycle",
	   "url" -> "/studyplans/cycles",
	   "title" -> "StudyPlan Cycle Integration Test",
	   "filds" -> List[String]("id", "name", "abbrName", "uri"),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map( 
	   "name" -> "subject",
	   "url" -> "/subjects",
	   "title" -> "Subject Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/subject/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "subjecttype",
	   "url" -> "/subjects/types",
	   "title" -> "Subject Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/subject/types/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "timeperiod",
	   "url" -> "/timeperiods",
	   "title" -> "Time Period Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "timeperiodtype",
	   "url" -> "/timeperiods/types",
	   "title" -> "Time Period Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/timeperiod/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),

	Map(
	   "name" -> "timesheettype",
	   "url" -> "/timesheets/types",
	   "title" -> "Timesheet Type Integration Test",
	   "filds" -> List[String](),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "data/timesheet/type/response.json",
	   "checkFieldsExistence"-> false,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> true,
   	   "chackWithOutParemetrs" -> true
	   ),
	   
	Map(
	   "name" -> "wavetype",
	   "url" -> "/wave/types",
	   "title" -> "Wave Type Get Paged Result",
	   "filds" -> List[String]("id", "name", "uri"),
	   "filter" -> Map[String,Any](),
	   "order" -> List[OrderBy](),
	   "pathData" -> "",
	   "checkFieldsExistence"-> true,
	   "checkOrder" -> false,
	   "checkOrderOne" -> false,
	   "checkFilter" -> false,
	   "checkFilterOne"-> false,
	   "checkData" -> false,
	   "chackWithOutParemetrs" -> true
	   )
	   
	 )
	 	
  val testCase = buildAllTestCase(data)
}
	