INSERT INTO q_rf_propertytype(abbrname, name, uid, utid, uapp, status, actual, note, crtuser, crtusergroup, create_date, update_date ) VALUES 
	('string', 'Стрічка', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('integer', 'Ціле', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('double', 'Число', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('date', 'Дата', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('image', 'Зображення', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('document', 'Документ', null, null, null, 'ACTIVE', 0, null, 'illay', 'public', now(), now()), 
	('file', 'Файл', null, null, null, 'ACTIVE', 0, null, 'illay', 'public', now(), now()), 
	('string-list', 'Стрічка (список)', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('integer-list', 'Ціле (список)', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('double-list', 'Число (список)', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('date-list', 'Дата (список)', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('ref', 'Посилання', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('inc', 'Включення', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('address', 'Адреса', null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now())
