INSERT INTO q_rf_enrolmenttype(abbrname, name, parent_id, uid, utid, uapp, status, actual, note, crtuser, crtusergroup, create_date, update_date ) VALUES 
	('сертифікат', 'За даними сертифікату', null, 1, null, 'edbo/PersonEnteranceTypes', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('іспит', 'За результатами іспитів', null, 2, null, 'edbo/PersonEnteranceTypes', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	('сертифікат+іспит', 'За даними сертифікатів та результатами іспитів', null, 3, null, 'edbo/PersonEnteranceTypes', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'іноземець за контрактом', 2, 1, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'громадяни, що звільнились із ЗСУ в цьому році', 2, 2, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'військовосл., що служать за контрактом (заочна ф.н.)', 2, 3, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'особи, що мають захворювання із переліку захворювань із Наказу 124/95 МОН/МОЗ', 2, 4, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'діти-інваліди (до 18 років), інваліди І-ІІ групи (від 18 років)', 2, 5, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'отримав ПЗСО в 2007 і раніше', 2, 6, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'другий (третій) предмет – творчий конкурс', 2, 7, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'перший предмет для не атестованих з української мови', 2, 8, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Громадяни України, які в рік вступу здобули повну загальну середню освіту за кордоном', 2, 9, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'особи, що проживають у Донецькій та Луганській областях та не проходили ЗНО (РКМУ від 27.08.2014р. №785-р)', 2, 10, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Вступ не по ЗНО', 2, 100, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Вступ з частковим набором предметів ЗНО', 2, 101, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Зарахування за співбесідою', 2, 105, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Учасник міжнародної олімпіади', 2, 106, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'іноземець за контрактом', 3, 1, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'громадяни, що звільнились із ЗСУ в цьому році', 3, 2, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'військовосл., що служать за контрактом (заочна ф.н.)', 3, 3, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'особи, що мають захворювання із переліку захворювань із Наказу 124/95 МОН/МОЗ', 3, 4, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'діти-інваліди (до 18 років), інваліди І-ІІ групи (від 18 років)', 3, 5, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'отримав ПЗСО в 2007 і раніше', 3, 6, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'другий (третій) предмет – творчий конкурс', 3, 7, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'перший предмет для не атестованих з української мови', 3, 8, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Громадяни України, які в рік вступу здобули повну загальну середню освіту за кордоном', 3, 9, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'особи, що проживають у Донецькій та Луганській областях та не проходили ЗНО (РКМУ від 27.08.2014р. №785-р)', 3, 10, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Вступ не по ЗНО', 3, 100, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Вступ з частковим набором предметів ЗНО', 3, 101, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Зарахування за співбесідою', 3, 105, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'Учасник міжнародної олімпіади', 3, 106, null, 'edbo/RequestExaminationCauses', 'ACTIVE', 1, null, 'illay', 'public', now(), now()), 
	(null, 'За даними сертифікату', 1, null, null, null, 'ACTIVE', 1, null, 'illay', 'public', now(), now())
