
package org.lnu.is.edbo.person_min;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EDBOPerson", targetNamespace = "http://edboservice.ua/", wsdlLocation = "file:///home/illya/workspace-idea/edbo client/src/person_min/Person_min.wsdl")
public class EDBOPerson
    extends Service
{

    private final static URL EDBOPERSON_WSDL_LOCATION;
    private final static WebServiceException EDBOPERSON_EXCEPTION;
    private final static QName EDBOPERSON_QNAME = new QName("http://edboservice.ua/", "EDBOPerson");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:./resource/Person_min.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EDBOPERSON_WSDL_LOCATION = url;
        EDBOPERSON_EXCEPTION = e;
    }

    public EDBOPerson() {
        super(__getWsdlLocation(), EDBOPERSON_QNAME);
    }

    public EDBOPerson(WebServiceFeature... features) {
        super(__getWsdlLocation(), EDBOPERSON_QNAME, features);
    }

    public EDBOPerson(URL wsdlLocation) {
        super(wsdlLocation, EDBOPERSON_QNAME);
    }

    public EDBOPerson(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EDBOPERSON_QNAME, features);
    }

    public EDBOPerson(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EDBOPerson(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EDBOPersonSoap
     */
    @WebEndpoint(name = "EDBOPersonSoap")
    public EDBOPersonSoap getEDBOPersonSoap() {
        return super.getPort(new QName("http://edboservice.ua/", "EDBOPersonSoap"), EDBOPersonSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EDBOPersonSoap
     */
    @WebEndpoint(name = "EDBOPersonSoap")
    public EDBOPersonSoap getEDBOPersonSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://edboservice.ua/", "EDBOPersonSoap"), EDBOPersonSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EDBOPERSON_EXCEPTION!= null) {
            throw EDBOPERSON_EXCEPTION;
        }
        return EDBOPERSON_WSDL_LOCATION;
    }

}
