//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.27 at 12:51:32 AM EET 
//


package org.is.lnu.edebo.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UniversityFacultetsGetRequests2BinResult" type="{http://edboservice.ua/}ArrayOfString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "universityFacultetsGetRequests2BinResult"
})
@XmlRootElement(name = "UniversityFacultetsGetRequests2BinResponse")
public class UniversityFacultetsGetRequests2BinResponse {

    @XmlElement(name = "UniversityFacultetsGetRequests2BinResult")
    protected ArrayOfString universityFacultetsGetRequests2BinResult;

    /**
     * Gets the value of the universityFacultetsGetRequests2BinResult property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getUniversityFacultetsGetRequests2BinResult() {
        return universityFacultetsGetRequests2BinResult;
    }

    /**
     * Sets the value of the universityFacultetsGetRequests2BinResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setUniversityFacultetsGetRequests2BinResult(ArrayOfString value) {
        this.universityFacultetsGetRequests2BinResult = value;
    }

}
